spring:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  datasource:
    username: sa
    url: jdbc:h2:mem:payment
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'


